// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: c575929542
// Version Date: 2020年 6月17日 星期三 04时40分15秒 UTC

// Package grpc provides a gRPC client for the SpiderServer service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/mogfee/gokit-demo/demo"
	"github.com/mogfee/gokit-demo/demo/spiderserver-service/svc"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.SpiderServerServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var parselistEndpoint endpoint.Endpoint
	{
		parselistEndpoint = grpctransport.NewClient(
			conn,
			"proto.SpiderServer",
			"ParseList",
			EncodeGRPCParseListRequest,
			DecodeGRPCParseListResponse,
			pb.ParseListResponse{},
			clientOptions...,
		).Endpoint()
	}

	var parsedetailEndpoint endpoint.Endpoint
	{
		parsedetailEndpoint = grpctransport.NewClient(
			conn,
			"proto.SpiderServer",
			"ParseDetail",
			EncodeGRPCParseDetailRequest,
			DecodeGRPCParseDetailResponse,
			pb.ParseDetailResponse{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		ParseListEndpoint:   parselistEndpoint,
		ParseDetailEndpoint: parsedetailEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCParseListResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC parselist reply to a user-domain parselist response. Primarily useful in a client.
func DecodeGRPCParseListResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.ParseListResponse)
	return reply, nil
}

// DecodeGRPCParseDetailResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC parsedetail reply to a user-domain parsedetail response. Primarily useful in a client.
func DecodeGRPCParseDetailResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.ParseDetailResponse)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCParseListRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain parselist request to a gRPC parselist request. Primarily useful in a client.
func EncodeGRPCParseListRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.ParseListRequest)
	return req, nil
}

// EncodeGRPCParseDetailRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain parsedetail request to a gRPC parsedetail request. Primarily useful in a client.
func EncodeGRPCParseDetailRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.ParseDetailRequest)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
