// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: c575929542
// Version Date: 2020年 6月17日 星期三 04时40分15秒 UTC

package svc

// This file contains methods to make individual endpoints from services,
// request and response types to serve those endpoints, as well as encoders and
// decoders for those types, for all of our supported transport serialization
// formats.

import (
	"context"
	"fmt"

	"github.com/go-kit/kit/endpoint"

	pb "github.com/mogfee/gokit-demo/demo"
)

// Endpoints collects all of the endpoints that compose an add service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
//
// In a service, it's useful for functions that need to operate on a per-endpoint
// basis. For example, you might pass an Endpoints to a function that produces
// an http.Handler, with each method (endpoint) wired up to a specific path. (It
// is probably a mistake in design to invoke the Service methods on the
// Endpoints struct in a service.)
//
// In a client, it's useful to collect individually constructed endpoints into a
// single type that implements the Service interface. For example, you might
// construct individual endpoints using transport/http.NewClient, combine them into an Endpoints, and return it to the caller as a Service.
type Endpoints struct {
	ParseListEndpoint   endpoint.Endpoint
	ParseDetailEndpoint endpoint.Endpoint
}

// Endpoints

func (e Endpoints) ParseList(ctx context.Context, in *pb.ParseListRequest) (*pb.ParseListResponse, error) {
	response, err := e.ParseListEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.ParseListResponse), nil
}

func (e Endpoints) ParseDetail(ctx context.Context, in *pb.ParseDetailRequest) (*pb.ParseDetailResponse, error) {
	response, err := e.ParseDetailEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.ParseDetailResponse), nil
}

// Make Endpoints

func MakeParseListEndpoint(s pb.SpiderServerServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.ParseListRequest)
		v, err := s.ParseList(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeParseDetailEndpoint(s pb.SpiderServerServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.ParseDetailRequest)
		v, err := s.ParseDetail(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

// WrapAllExcept wraps each Endpoint field of struct Endpoints with a
// go-kit/kit/endpoint.Middleware.
// Use this for applying a set of middlewares to every endpoint in the service.
// Optionally, endpoints can be passed in by name to be excluded from being wrapped.
// WrapAllExcept(middleware, "Status", "Ping")
func (e *Endpoints) WrapAllExcept(middleware endpoint.Middleware, excluded ...string) {
	included := map[string]struct{}{
		"ParseList":   struct{}{},
		"ParseDetail": struct{}{},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc, _ := range included {
		if inc == "ParseList" {
			e.ParseListEndpoint = middleware(e.ParseListEndpoint)
		}
		if inc == "ParseDetail" {
			e.ParseDetailEndpoint = middleware(e.ParseDetailEndpoint)
		}
	}
}

// LabeledMiddleware will get passed the endpoint name when passed to
// WrapAllLabeledExcept, this can be used to write a generic metrics
// middleware which can send the endpoint name to the metrics collector.
type LabeledMiddleware func(string, endpoint.Endpoint) endpoint.Endpoint

// WrapAllLabeledExcept wraps each Endpoint field of struct Endpoints with a
// LabeledMiddleware, which will receive the name of the endpoint. See
// LabeldMiddleware. See method WrapAllExept for details on excluded
// functionality.
func (e *Endpoints) WrapAllLabeledExcept(middleware func(string, endpoint.Endpoint) endpoint.Endpoint, excluded ...string) {
	included := map[string]struct{}{
		"ParseList":   struct{}{},
		"ParseDetail": struct{}{},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc, _ := range included {
		if inc == "ParseList" {
			e.ParseListEndpoint = middleware("ParseList", e.ParseListEndpoint)
		}
		if inc == "ParseDetail" {
			e.ParseDetailEndpoint = middleware("ParseDetail", e.ParseDetailEndpoint)
		}
	}
}
